# Generated by Django 3.1.5 on 2021-03-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployeeprofile',
            name='employee_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
