# Generated by Django 3.1.5 on 2021-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0002_auto_20210330_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='newemployeeprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
